#!/bin/bash

# check if required directories exist if not create them

DOCUMENTS_DIR="$HOME/Documents/"
LOCAL_BIN_DIR="$HOME/.local/bin"
WALLPAPERS_DIR="$HOME/Pictures/wallpapers"
WALL_DEFAULT_DIR="$WALLPAPERS_DIR/default/"
SCREENSHOTS_DIR="$HOME/Pictures/screenshots"
RECORDINGS_DIR="$HOME/Pictures/recordings"

if [ ! -d "$DOCUMENTS_DIR" ]; then
    mkdir -p "$DOCUMENTS_DIR"
fi
if [ ! -d "$LOCAL_BIN_DIR" ]; then
    mkdir -p "$LOCAL_BIN_DIR"
fi
if [ ! -d "$WALLPAPERS_DIR" ]; then
    mkdir -p "$WALLPAPERS_DIR"
fi
if [ ! -d "$WALL_DEFAULT_DIR" ]; then
    mkdir -p "$WALL_DEFAULT_DIR"
fi
if [ ! -d "$SCREENSHOTS_DIR" ]; then
    mkdir -p "$SCREENSHOTS_DIR"
fi

if [ ! -d "$RECORDINGS_DIR" ]; then
    mkdir -p "$RECORDINGS_DIR"
fi

# stow hosts first
if [ "$(hostname)" = "archlinux-desktop" ]; then
  # stow package for desktop
  stow -R desktop -t ~/.config/
elif [ "$(hostname)" = "archlinux-laptop" ]; then
  # stow packages for laptop
  stow -R laptop -t ~/.config/
else
  echo "Unknown host: $(hostname)"
fi

# stow main second
stow main -t ~/.config

# stow scripts third
stow scripts -t ~/.local/bin

# stow wallpapers fourth
stow wallpapers -t ~/Pictures/wallpapers

# stow special packages
stow -d ./special wrappedhl -t ~/.local/bin
stow -d ./special zshenv -t ~/
stow -d ./special bash -t ~/
stow -d ./special vim -t ~/
stow -d ./special ideavimrc -t ~/
