require("core.colorscheme")
require("core.keymaps")
require("core.options")

require("misc.misc")

require("plugins.plugins-declaration")
require("plugins.conf.alpha-nvim.alpha-nvim")
require("plugins.conf.comment.comment")
require("plugins.conf.gitsigns.gitsigns")
require("plugins.conf.lspsaga.lspsaga")
require("plugins.conf.lualine.lualine")
require("plugins.conf.mason.mason")
require("plugins.conf.neodev.neodev")
require("plugins.conf.null-ls.null-ls")
require("plugins.conf.nvim-autopairs.nvim-autopairs")
require("plugins.conf.nvim-cmp.nvim-cmp")
require("plugins.conf.nvim-neo-tree.nvim-neo-tree")
require("plugins.conf.nvim-treesitter.nvim-treesitter")
require("plugins.conf.project.project")
require("plugins.conf.structlog.structlog")
require("plugins.conf.telescope.telescope")
require("plugins.conf.toggleterm.toggleterm")
require("plugins.conf.which-key.which-key")
